// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWktXExM23mDAHSmhzPAmX2awPEA17Unc',
    appId: '1:915984881840:web:2321c550ca89cc7e3cc375',
    messagingSenderId: '915984881840',
    projectId: 'practiseapp-67d8a',
    authDomain: 'practiseapp-67d8a.firebaseapp.com',
    storageBucket: 'practiseapp-67d8a.appspot.com',
    measurementId: 'G-T8HXX6FZ99',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_VrjeJOJq30anqcCJAmXEZzjp6_Qb67s',
    appId: '1:915984881840:android:bf5ce18b87da90633cc375',
    messagingSenderId: '915984881840',
    projectId: 'practiseapp-67d8a',
    storageBucket: 'practiseapp-67d8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmF9IzB9DCBDFeRg6L8yTs3H8QqWKAkW4',
    appId: '1:915984881840:ios:2b056e29ef5a5d523cc375',
    messagingSenderId: '915984881840',
    projectId: 'practiseapp-67d8a',
    storageBucket: 'practiseapp-67d8a.appspot.com',
    iosBundleId: 'com.example.practiceApp1',
  );
}
